
const UserModel = require('../../../models/user');
//jsonwebtoken is used to generate a token, ie; the jwt token is generated by sign function of jsonwebtoken library
const jwt = require('jsonwebtoken');
const properties = require('../../../config/properties');

module.exports.createSession = async function(req, res){
    try{
        let userFound = await UserModel.findOne({email: req.body.email});
        if (!userFound || userFound.password != req.body.password){
            return res.json(422, {
                message: "Invalid username/password"
            });
        }

        //returning success code along with the jwt token generated
        return res.json(200, {
            message: 'User signed in successfully, sending back the jwt token',
            data:  {
                token: jwt.sign(userFound.toJSON(), properties.jwt_secret_key, {expiresIn:  '900000'})
            }
        });

    }catch(err){
        console.log('Error:', err);
        return res.json(500, {
            message: "Internal Server Error"
        });
    }
}